apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hestia-shield.fullname" . }}-secret
  labels:
    {{- include "hestia-shield.labels" . | nindent 4 }}
type: Opaque
stringData:
  HESTIA_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- if not .Values.postgresql.enabled }}
  HESTIA_DATABASE_URL: {{ include "hestia-shield.postgresql.url" . }}
  {{- end }}
  {{- if not .Values.redis.enabled }}
  HESTIA_REDIS_URL: {{ include "hestia-shield.redis.url" . }}
  {{- end }}
